# -*- coding: utf-8 -*-
"""task44-no-get_dummies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/YakovZhurkin/b25d2a471ef49d92a423124918453ec4/task44-no-get_dummies.ipynb
"""

import pandas as pd

import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head(25)

result_data = data.copy()

result_data.head()

unique_values = data['whoAmI'].unique()

column_robot = {'robot':'1','human':'0'}

column_human = {'robot':'0','human':'1'}

result_data['human'] = result_data['whoAmI'].map(column_human)

result_data['robot'] = result_data['whoAmI'].map(column_robot)

result_data.head(20)

"""Я понимаю что код не автоматизирован под другие переменные и 84 строка по мойму не обязательнаБ но как смог так и сделал)))Спасибо вам за семинары вы прекрасный преподователь!)"""